pipeline {
    agent any

    tools {
        maven 'Maven-3.8.7'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Anahayerramilli/devsecops-demo.git'
            }
        }

        stage('Build & Test') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonarqube') {
                    sh '''
                        mvn org.sonarsource.scanner.maven:sonar-maven-plugin:5.8.0.7211:sonar
                    '''
                }

                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                    docker build \
                      -f Devops/Dockerfile \
                      -t devsecops-demo:1.0 .
                '''
            }
        }

        stage('Trivy Scan') {
            steps {
                sh '''
                    trivy image \
                      --format json \
                      --output trivy-report.json \
                      devsecops-demo:1.0

                    trivy image \
                      --severity HIGH,CRITICAL \
                      --exit-code 1 \
                      devsecops-demo:1.0
                '''
            }

            post {
                always {
                    archiveArtifacts artifacts: 'trivy-report.json',
                                     allowEmptyArchive: false
                }
            }
        }

        stage('Docker Push') {
            steps {
                script {
                    def imageTag = "build-${env.BUILD_NUMBER}"

                    sh """
                        docker tag devsecops-demo:1.0 \
                        anaha2211/devsecops-demo:${imageTag}
                    """

                    withCredentials([usernamePassword(
                        credentialsId: 'dockerhub-credentials',
                        usernameVariable: 'DOCKER_USERNAME',
                        passwordVariable: 'DOCKER_PASSWORD'
                    )]) {
                        sh '''
                            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

                            docker push anaha2211/devsecops-demo:build-${BUILD_NUMBER}
                        '''
                    }
                }
            }
        }

        stage('Kubernetes Deploy') {
            steps {
                sh '''
                    kubectl --kubeconfig /tmp/jenkins-config \
                      -n devsecops \
                      set image deployment/devsecops-demo \
                      devsecops-demo=anaha2211/devsecops-demo:build-${BUILD_NUMBER}

                    kubectl --kubeconfig /tmp/jenkins-config \
                      -n devsecops \
                      rollout status deployment/devsecops-demo \
                      --timeout=120s
                '''
            }
        }
    }
}
